DigitalCart/DigitalCart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path



urlpatterns = [
    path("", include('app1.urls')),
    path('admin/', admin.site.urls),
    path('items/', include('app2.urls')),
    path('', include('app3.urls') ),
   

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DigitalCart/app1/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from .views import search_products




urlpatterns=[
    path("", views.index, name='index'),
    path("about/", views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('search/', views.search, name='search'),
    path('signin/',views.Signin),
    path('signup/',views.Signup),
    path('signout/',views.Signout),
    path('description/',views.Des),
    path('instractions/',views.Instractions),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('Password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset_form.html'), name='Password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
    path('individualsell',views.Individualsell),
    path('sell',views.Sell),
    path('category',views.Categories),
    # path('<int:pk>/', views.product_detail, name='product_detail'),
    # path('make_order/', views.make_order, name='make_order'),
    # path('add_comment/', views.add_comment, name='add_comment'),
    path('product_list/', views.product_list, name='product_list'),
    path('Products/<int:pk>/', views.ProductDetailView.as_view(), name='product'),
    # path('login/',views.Login_register,name='login'),
    # path('sell/',views.Sell,name='sell'),
    path('profile_update/', views.profile_update, name='profile_update.html'),
    path('about/', views.about, name='about'),
    path('search/',views.search, name='search'),
    path('contact_us/',views.contact),
    
]

DigitalCart/app2/urls.py
from django.urls import path

from . import views


app_name = 'app2'

urlpatterns = [
    # path('search/', views.search, name='search'),
    path('<int:pk>/', views.detail, name='detail'),
    path('register/', views.register_business,name='register_business'),
    path('categories/<int:pk>/', views.category, name='categorypage'),
]

DigitalCart/app1/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.conf import settings
#from .views import Product, Comment
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

class Business(models.Model):
    name=models.CharField(max_length=50)
    contact_details=models.CharField(max_length=20)
    location=models.CharField(max_length=50)
    description=models.TextField()
    
class Category(models.Model):
    name=models.CharField(max_length=50)
    def __str__(self):
        return self.name

class Product (models.Model):
    name=models.CharField(max_length=50)
    price=models.DecimalField(default=0,decimal_places=2,max_digits=7)
    description=models.CharField(max_length=250)
    category=models.ForeignKey(Category,on_delete=models.CASCADE,default=1)
    image=models.ImageField(upload_to='uploads/Product/')
    #seller = models.ForeignKey(User, on_delete=models.CASCADE,default=1)
    def __str__(self):
        return self.name
    
class Customer(models.Model):
    fname=models.CharField(max_length=50)
    lname=models.CharField(max_length=50)
    email=models.CharField(max_length=50)
    phoneN=models.CharField(max_length=20)
    password=models.CharField(max_length=20)

    def __str__(self):
        return f"{self.fname } {self.lname}"

# class Comment(models.Model):
#        user = models.ForeignKey(User, on_delete=models.CASCADE)
#        product = models.ForeignKey(Product, on_delete=models.CASCADE)
#        text = models.TextField()
       

    
class Order(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    #user = models.ForeignKey(User, on_delete=models.CASCADE,default=1) 
    customer=models.ForeignKey(Customer,on_delete=models.CASCADE)
    address=models.CharField(max_length=50,blank=True)
    quantity=models.IntegerField(default=1) 
    phoneN=models.CharField(max_length=20)
    date=models.DateField(default=datetime.datetime.today)
    status=models.BooleanField(default=False)
    def __str__(self):
        return self.product

DigitalCart/app1/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
#from .models import Order, Business ,Comment, Customer
from django.contrib.auth.forms import UserCreationForm


class profileupdateform(UserChangeForm):
   password = None
   fname=forms.CharField(max_length=50),
   lname=forms.CharField(max_length=50),
   email=forms.CharField(max_length=50),
   phoneN=forms.CharField(max_length=20),

class SignupForm(UserCreationForm):
   class Meta:
      model = User

#class Meta:
 #       model = User
  #      fields = ('fname','lname', 'email', 'phoneN')

    
# class BusinessCreateForm(forms.ModelForm):
#     class Meta:
#         model = Business 
#         fields = ['name', 'contact_details', 'location', 'description']

# class CustomerForm(forms.ModelForm):
#     class Meta:
#         model = Customer
#         fields = ['fname', 'lname', 'email', 'phoneN','password' ]     
             
# class OrderForm(forms.ModelForm):
#     class Meta:
#         model = Order
#         fields = ['product', 'quantity', 'user']

# class CommentForm(forms.ModelForm):
#     class Meta:
#         model = Comment
#         fields = ['product', 'user', 'text']
   

DigitalCart/app1/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.contrib import messages 
#from .forms import OrderForm, CommentForm, BusinessCreateForm, CustomerForm
#from .forms import profileupdateform
from .models import Product, Customer
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from DigitalCart import settings
from django.core.mail import send_mail,EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_decode
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes, force_str
from .tokens import generate_token
#import stripe
from django.conf import settings
from django.shortcuts import render

from app2.models import Category, Item

from django.shortcuts import render
from .models import Product
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from .models import Product

def search_products(request):
    query = request.GET.get('q')
    if query:
        products = Product.objects.filter(name_icontains=query) | Product.objects.filter(seller_icontains=query)
    else:
        products = Product.objects.all()
    return render(request, 'search_results.html', {'products': products})

def index(request):
    return render(request,'index.html')
def profile_update(request):
    if request.method == "POST":
        password=request.POST['password']

    return render(request, 'profile_update.html')

def Signup(request):
    if request.method == "POST":
        username=request.POST['username']
        fname=request.POST['fname']
        lname=request.POST['lname']
        email=request.POST['email']
        password=request.POST['password']
        Cpassword=request.POST['Cpassword']

        if User.objects.filter(email=email):
            messages.error(request,"Email already registered")
            return redirect("/signup")
        if User.objects.filter(username=username):
            messages.error(request,"Username taken")
            return redirect("/signup")
        if len(username)>15:
            messages.error(request,"Username can't exceed 15 characters")
            return redirect("/signup")
        if password !=Cpassword:
            messages.error(request,"Passwords don't match")
            return redirect("/signup")
        if len(password)<8:
            messages.error(request,"Password should have more than 8 characters")
            return redirect("/signup")

        if not username.isalnum():
            messages.error(request,"Username can only contain numbers and letters")
            return redirect("/signup")   
        else:
            myuser=User.objects.create_user(username,email,password)
            myuser.first_name=fname
            myuser.last_name=lname
            myuser.is_active=False
            myuser.save()

        messages.success(request,"Account created successfuly.")
        #welcome email
        subject="Welcome to Digital Cart"
        message="Hello "+ myuser.first_name+"!\n"+"An activation link will be sent to you shortly.} "
        from_email= settings.EMAIL_HOST_USER
        to_list= [myuser.email]
        send_mail(subject,message,from_email,to_list,fail_silently=True)
        #confirmation email
        current_site= get_current_site(request)
        email_subject= "Comfirm your email @digitalcart"
        message2= render_to_string('email_comf.html',{
           'name': myuser.first_name,
           'domain': current_site.domain,
           'uid':urlsafe_base64_encode(force_bytes(myuser.pk)), 
           'token': generate_token.make_token(myuser),
        })
        email=EmailMessage(
            email_subject,
            message2,
            settings.EMAIL_HOST_USER,
            [myuser.email],
            )
        email.fail_silently= True,
        email.send()
        return redirect('/instractions')

        # messages.success(request,"Account created successfuly")
        # return redirect('/app1/signin')
    return render(request,'signup.html')

def Signin(request):
    if request.method == "POST":
        username=request.POST['username']
        password=request.POST['password']
        user=authenticate(username=username,password=password)

        if user is not None:
            login(request,user)
            # fname=user.first_name
            return render(request,'index.html')
        else:
            messages.error(request,"Incorrect password or username")
            return redirect('/signin')

    return render(request,'signin.html')
def activate(request,uidb64,token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        myuser = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        myuser = None   
    if myuser is not None and generate_token.check_token(myuser,token):
        myuser.is_active = True  
        myuser.save()
        login(request, myuser)
        return redirect('index')
    else:
        return render(request, 'activation_failed.html') 



def Signout(request):
    logout(request)
    messages.success(request,"Log out successful")
    return redirect('index')

def Des(request):
    return render(request,'description.html')
def Instractions(request):
    return render(request,'instractions.html')

def Sell(request):
    return render(request,'sell.html')
def Individualsell(request):
    return render(request,'individualsell.html')
def Categories(request):
    return render(request,'categorypage.html')
# def form(request):
#     return render(request,'form.html')    
def product_list(request):
    products = Product.objects.all()
    return render(request, 'product_list.html', {'products': products})

# def product_detail(request, pk):
#     product = Product.objects.get(pk=pk)
#     comments = Comment.objects.filter(product=product)
#     return render(request, 'product_detail.html', {'product': product, 'comments': comments}) 
  
# def add_comment(request):
#     if request.method == 'POST':
#         comment_form = CommentForm(request.POST)
#         if comment_form.is_valid():
#             comment_form.save()
#             return redirect('index')
#     return redirect('index')

# def make_order(request):
#     if request.method == 'POST':
#         order_form = OrderForm(request.POST)
#         if order_form.is_valid():
#             order_form.save()
#             return redirect('/app1/index')
#     return redirect('/app1/index')


    
class ProductCreateView(CreateView):
    model = Product
    fields = ['name', 'price', 'description', 'category', 'image', 'seller']
    template_name = 'products/product_form.html'  
    success_url = '/product_list/'      

    
class ProductDetailView(DetailView):
    model = Product
    template_name = 'product_detail.html'  
    context_object_name = 'product' 


# def create_business(request):
#     if request.method == 'POST':
#         form = BusinessCreateForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('business_profile')  
#     else:
#         form = BusinessCreateForm()
#     return render(request, 'create_business.html', {'form': form})

# def Customer(request):
#     if request.method == 'POST':
#         form = CustomerForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('customer_profile')


# 
def index(request):
    items=Item.objects.all()
    Categories=Category.objects.all()
    return render(request, 'index.html', {
        'items':items,
        'categories':Categories
    })
def about(request):
    return render(request, 'about.html')

def contact(request):
    return render(request, 'contact.html')

def search(request):
    return render(request, 'search.html', {})

def add_to_cart(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    
    # Assuming you're using sessions to store cart items
    cart = request.session.get('cart', {})
    cart[product_id] = cart.get(product_id, 0) + 1
    request.session['cart'] = cart
    
    return redirect('product-detail', pk=product_id)


def cart_view(request):
    cart = request.session.get('cart', {})
    cart_items = []
    
    for product_id, quantity in cart.items():
        product = get_object_or_404(Product, pk=product_id)
        cart_items.append({
            'product': product,
            'quantity': quantity,
        })
    
    return render(request, 'cart.html', {'cart_items': cart_items})

DigitalCart/app1/templates/activation_failed.html
{% autoescape off %}
Activation failed
{% endautoescape %}

DigitalCart/app1/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DigitalCart</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css" />
</head>
<body>
    {% include 'navbar.html' %}

    {% block content %}

    {% endblock %}

<div class="footer-info">
    <div class="container">
        <div class="wrapper">
            <div class="flexcol">
                <div class="logo">
                    <a href="#"><span class="circle"></span>.DigitalCart</a>
                </div>
                <div class="socials">
                    <ul class="flexitem">
                        <li><a href="#"><i class="ri-twitter-line"></i></a></li>
                        <li><a href="#"><i class="ri-facebook-fill"></i></a></li>
                        <li><a href="#"><i class="ri-instagram-line"></i></a></li>
                        <li><a href="#"><i class="ri-youtube-line"></i></a></li>
                        <li><a href="#"><i class="ri-linkedin-fill"></i></a></li>
                    </ul>
                </div>
            </div>
            <p class="mini-text">Copyright 2024 © .DigitalCart. All rights reserved.</p>
        </div>
    </div>
</div>
<!-- footer -->

<div class="menu-bottom desktop-hide">
    <div class="container">
        <div class="wrapper">
            <nav>
                <ul class="flexitem">
                    <li>
                        <a href="#">
                            <i class="ri-bar-chart-line"></i>
                            <span>Trending</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="ri-user-6-line"></i>
                            <span>Account</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="ri-heart-line"></i>
                            <span>Wishlist</span>
                        </a>
                    </li>
                    <li>
                        <a href="#0" class="t-search">
                            <i class="ri-search-line"></i>
                            <span>Search</span>
                        </a>
                    </li>
                    <li>
                        <a href="#0">
                            <i class="ri-shopping-cart-line"></i>
                            <span>Cart</span>
                            <div class="fly-item">
                                <span class="item-number">0</span>
                            </div>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</div>
<!-- menu bottom -->

<div class="search-bottom desktop-hide">
    <div class="container">
        <div class="wrapper">
            <form action="" class="search">
                <a href="#" class="t-close search-close flexcenter"><i class="ri-close-line"></i></a>
                <span class="icon-large"><i class="ri-search-line"></i></span>
                <input type="search" placeholder="Search">
                <button type="submit">Search</button>
            </form>
        </div>
    </div>
</div>
<!-- search bottom -->

<div class="overlay">

</div>
<!-- overlay -->
</div>


<script src="https://unpkg.com/swiper@8/swiper-bundle.min.js"></script>    
<script src="https://cdnjs.cloudflare.com/ajax/libs/fslightbox/3.4.1/index.js"></script>
<script src="{% static 'script.js' %}"></script>
</body>
</html>

DigitalCart/app1/templates/categorypage.html
{% extends 'base.html' %}

{% include 'navbar.html' %}


{% block content %}

<div class="features">
    <div class="container">
        <div class="wrapper">
            <div class="column">
                <div class="sectop flexitem">
                    <h2><span class="circle"></span><span>{{ category.name }}</span></h2>
                    <div class="second-links">
                        <a href="#" class="view-all">View All<i class="ri-arrow-right-line"></i></a><br>
                    </div>
                </div>
                <div class="products main flexwrap">

                    {% for product in products %}

                    <div class="item">
                        <div class="media">
                            <div class="thumbnail object-cover">
                                <a href="#">
                                    <img src="{{ product.image.url }}" alt="">
                                </a>
                            </div>
                            <div class="hoverable">
                                <ul>
                                    <li class="active"><a href="#" class="social-info">
                                        <span><i class="ri-heart-line"></i></span>
                                        <p class="hover-text">Wishlist</p>
                                    </a></li>
                                    <li><a href="#" class="social-info">
                                        <span><i class="ri-eye-line"></i></span>
                                        <p class="hover-text">View more</p>
                                    </a></li>
                                    <li><a href="#" class="social-info">
                                        <span><i class="ri-shopping-cart-line"></i></span>
                                        <p class="hover-text">Add to Cart</p>
                                    </a></li>
                                </ul>
                            </div>
                            <div class="discount circle flexcenter"><span>50%</span></div>
                        </div>
                        <div class="content">
                            <div class="rating">
                                <div class="stars"></div>
                                <span class="mini-text">(17,098)</span>
                            </div>
                            <h3><a href="#">{{ product.name }}</a></h3>
                            <div class="price">
                                <span class="current">{{ product.sellingprice }}UGX</span>
                                <span class="normal mini-text">{{ product.globalprice }}UGX</span>
                            </div>
                            <div class="footer">
                                <ul class="mini-text">
                                    <li>{{ product.description }}</li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    {% endfor %}



                    {% for item in items %}

                    <div class="item">
                        <div class="media">
                            <div class="thumbnail object-cover">
                                <a href="{% url 'app2:detail' item.id %}">
                                    <img src="{{ item.image.url }}" alt="">
                                </a>
                            </div>
                            <div class="hoverable">
                                <ul>
                                    <li class="active"><a href="#" class="social-info">
                                        <span><i class="ri-heart-line"></i></span>
                                        <p class="hover-text">Wishlist</p>
                                    </a></li>
                                    <li><a href="#" class="social-info">
                                        <span><i class="ri-eye-line"></i></span>
                                        <p class="hover-text">View more</p>
                                    </a></li>
                                    <li><a href="#" class="social-info">
                                        <span><i class="ri-shopping-cart-line"></i></span>
                                        <p class="hover-text">Add to Cart</p>
                                    </a></li>
                                </ul>
                            </div>
                            <div class="discount circle flexcenter"><span>{{ item.discounted_price }}%</span></div>
                        </div>
                        <div class="content">
                            <div class="rating">
                                <div class="stars"></div>
                                <span class="mini-text">(17,098)</span>
                            </div>
                            <h3><a href="#">{{ item.name }}</a></h3>
                            <div class="price">
                                <span class="current">{{ item.sellingprice }}UGX</span>
                                <span class="normal mini-text">{{ item.globalprice }}UGX</span>
                            </div>
                            <div class="footer">
                                <ul class="mini-text">
                                    <li>{{ item.description }}</li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

DigitalCart/app1/templates/contact.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <title>Contact Us | Digital Cart</title>
    <link rel="stylesheet" href="contact.css" />
  </head>
  <body>
    <style>
      body {
        font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f7f7f7;
      }
      header {
        background-color: #e409f0;
        color: #fff;
        text-align: center;
        padding: 1rem 0;
      }
      main {
        display: flex;
        justify-content: space-around;
        margin-top: 2rem;
        padding: 0 10%;
      }

      .contact-info,
      .contact-form {
        width: 45%;
        background-color: #fff;
        padding: 2rem;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      }
      .contact-form {
        background-color: #f0f0f0;
        border-radius: 15px;
        box-sizing: border-box;
        padding: 40px;
        width: 100%;
        height: 100%;
      }
      .contact-form form {
        display: flex;
        flex-direction: column;
      }
      .contact-form label {
        margin-bottom: 0.5rem;
        font-weight: 600;
      }
      .contact-form input,
      .contact-form textarea {
        margin-bottom: 1rem;
        padding: 0.5rem;
        border: 1px solid #ccc;
        border-radius: 5px;
        height: 40px;
        line-height: 40px;
        border-radius: 20px;
      }
      .contact-form textarea {
        height: 80px;
        line-height: 40px;
        border-radius: 20px;
      }
      .contact-form button {
        padding: 0.5rem 1rem;
        background-color: #e409f0;
        color: #fff;
        border: none;
        border-radius: 20px;
        cursor: pointer;
        transition: background-color 0.3s ease;
      }
      .contact-form button:hover {
        background-color: #e409f0; /* Darker shade for hover effect */
      }
      h2 {
        color: black; /* Brand color */
        text-transform: uppercase;
        border-bottom: 2px solid black; /* Border under h2 elements */
        padding-bottom: 10px;
      }
    </style>
    <header>
      <h1>Contact digitalcart</h1>
    </header>
    <main>
      <section class="contact-info">
        <h2>Contact Information</h2>
        <p>Email: contact@digitalcart.com</p>
        <p>Phone: +256 707-833-143</p>
        <div class="container">
            <h3>reach out to us on socialmedia</h3>
            <div class="social-icons">
              <a href="#"><i class="fab fa-facebook-f"></i></a>
              <a href="#"><i class="fab fa-twitter"></i></a>
              <a href="#"><i class="fab fa-instagram"></i></a>
              <a href="#"><i class="fab fa-youtube"></i></a>
              <a href="#"><i class="fab fa-linkedin"></i></a>
            </div>
      </section>
      <section class="contact-form">
        <h2>write to us</h2>
        <form action="/contact_us/" method=POST>
          {% csrf_token %}
  
          <div class="form-box">
              <!------------------- Contact form -------------------------->
              <div class="register-container" id="register">
                  
                  <div class="input-box">
  
                      <input type="text" id="username" name="username" class="input-field" placeholder="Create a username" required>
  
                      <i class="bx bx-user"></i>
                  </div>
                  <div class="two-forms">
                      <div class="input-box">
  
                          <input type="text" id="email" name="fname" class="input-field" placeholder="email" required>
  
                          <i class="bx bx-user"></i>
                      </div>
                      <div class="input-box">
                        <textarea id="message" name="message" class="input-field" placeholder="Enter your message" required></textarea>
                        <i class="bx bx-user"></i>
                    </div>
                    
                  </div>
                 
                  
                  
                  
                  <button class="sumbit">
                    <span class="btnText">Submit</span>
                    <i class="uil uil-navigator"></i>
                      
                  </div>
                 
              </div>
          </div>
      </form>
      </section>
    </main>
  </body>
</html>

DigitalCart/app1/templates/password_reset_confirm.html
{% block content %}
{% if validlink %}
    <h3> Change Password</h3>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Change password</button>
    </form>
{% else %}
<p>
    The password reset link was invlaid, possibly because it has already been used.
    Please request a new password reset link.
</p>  
{% endif %}  

{% endblock %}  

DigitalCart/app1/templates/password_reset_done.html
{% block content %}
<p>We have emailed you instructions for setting your password, if an account exists with the email you entered. 
    You should receive them shortly.
</p>
<p>
    If you do not receive an email, please make sure you have entered the address you registered with, 
    and check your spam folder.
</p>

{% endblock %}    

DigitalCart/app1/templates/password_reset_form.html
{% block content %}
    <h3>Forgot password</h3>
    <form method = 'POST'>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" name="send email">
    </form>
{% endblock %}    

DigitalCart/app1/templates/profile_update.html
{% block content %}
    <h3>Profile Update</h3>
    <form method = 'POST' action="/app1/profile_update/">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Update</button>
    </form>
{% endblock %}    

DigitalCart/app1/templates/register_business.html
{% extends 'base.html' %}
{% block content %}
<form method="POST" novalidate>
    {% csrf_token %}
    <h2>Register Business</h2>
    {{ form.as_p }}
    <input type="submit" value="Register" />
</form>
{% endblock content %}